name: Build & Publish Docker image

on:
  push:
    branches:
      - release-10.11.z
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Optional but useful: unique tag for each build
      - name: Set short sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push images (DockerHub)
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: .
          file: ./docker/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jellyfin:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/jellyfin:${{ env.VERSION }}-${{ env.SHORT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/jellyfin:pragma-latest
